### PR TITLE
Add Alert component

### PR DESCRIPTION
**Pull request by mfrachet**
Example: https://design-system-git-add-alert-strapijs.vercel.app/

NOTE: I've moved the link color to 700 because there was a constrat issue with 600

## API

```jsx
<Alert title="Success variant" variant="success" onClose={() => {}} closeLabel="Close notification">
    Alert with title and longer description
</Alert>
```

## Look

The Alert component running in storybook

### CODE REVIEW

**Comment by HichamELBSI** [comment]
@maevalienard Is this the component that will be used as a notification to alert that a new version is available?
If so, maybe we should think about the left link.

Screenshot 2021-05-07 at 11 29 37

**Comment by maevalienard** [comment]
You're right Hicham! I'll add this to my to-do and come back to you next week! 

The S size has a ":" after the title (Information alert, warning alert, success alert) :D Apart from this, amazing work, thanks!

**Comment by maevalienard** [comment]
Capture d’écran 2021-05-10 à 11 12 23

Hi, here are the updates requested :)

**Comment by HichamELBSI** [comment]
Is this PR still a draft?

**Review by HichamELBSI — APPROVED** [review]
LGTM 👍🏽  Good job!!

**Comment by maevalienard** [comment]
I saw you merged, I see you ignoring my comment 👁️ 😄

**Pull request merged**
