### PR TITLE
Add Modal Layout

### PR DESCRIPTION
**Pull request by mfrachet**
# ModalLayout

## Description

Add a ModalLayout, ModalHeader, ModalBody, ModalFooter to compose dialogs

## Demo

Example on : https://design-system-git-modal-layout-strapijs.vercel.app/?path=/story/design-system-layouts-modallayout--base

## API

```jsx
<ModalLayout onClose={() => undefined} labelledBy="title">
  <ModalHeader>
    <TextButton textColor="neutral800" as="h2" id="title">
      Title
    </TextButton>
  </ModalHeader>
  <ModalBody>Hello world</ModalBody>
  <ModalFooter
    startActions={<Button variant="tertiary">Cancel</Button>}
    endActions={
      <>
        <Button variant="secondary">Add new stuff</Button>
        <Button>Finish</Button>
      </>
    }
  />
</ModalLayout>
```

## Voiceover

Navigating a dialog using the keyboard and VoiceOver

### CODE REVIEW

**Review by maevalienard — APPROVED** [review]
Does the modal have a fix width? :D I forgot to mention it in the doc but it should be :) 

Otherwise, great job! Thank you!

**Comment by mfrachet** [comment]
> Does the modal have a fix width? :D I forgot to mention it in the doc but it should be :)

I've taken 800 as a maxwidth, and a padding of 32px on each side when the width of the viewport is less than 800

**Comment by maevalienard** [comment]
We have an 830px width size on the design side, is there a chance to adjust to this please? :)

**Comment by mfrachet** [comment]
sure 😊

**Review by soupette — APPROVED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]
That's so nice ! Good job @mfrachet

**Pull request merged**
