### PR TITLE
Next iteration

### PR DESCRIPTION
**Pull request by mfrachet**
Experimentation to create 3 different layouts (in Figma -> patterns)

- http://localhost:3000/one-block

One block layout in a create-react-app

- http://localhost:3000/two-cols

Two cols layout in a create-react-app

- http://localhost:3000/grid
- 
Grid layout in a create-react-app

### CODE REVIEW

**Comment by HichamELBSI** [comment]
😮  That's a very nice job! Maybe we can add another example with a submenu 

Screenshot 2021-06-01 at 10 36 13

**Comment by HichamELBSI** [comment]
> 😮 That's a very nice job! Maybe we can add another example with a submenu
> 
> Screenshot 2021-06-01 at 10 36 13

**Comment by mfrachet** [comment]
We don't have the compo for the side nav 😅

**Review by HichamELBSI — APPROVED** [review]
LGTM !!

**Pull request merged**
