### PR TITLE
Fixing vertical alignment in Alert

### PR DESCRIPTION
**Pull request by mfrachet**
The alert component shown in storybook

https://design-system-git-fix-link-alignment-strapijs.vercel.app/?path=/story/alert--base

### CODE REVIEW

**Comment by maevalienard** [comment]
Looks better, thank you :) Can we maybe central align the external link icon?

**Comment by mfrachet** [comment]
> Looks better, thank you :) Can we maybe central align the external link icon?

because of the two different font-size, line-heights and the wrapping behaviour expected when being on a bigger Alert, I can't manage to make these aligned 100%. I'm still having those 3px difference somewhere

**Comment by mfrachet** [comment]
cc @maevalienard

**Comment by maevalienard** [comment]
I don't see any difference?

**Review by soupette — APPROVED** [review]
LGTM

**Comment by mfrachet** [comment]
cc @maevalienard 

The alert component with and without the 1px additional margin

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Pull request merged**
