### PR TITLE
Adding searchbar component

### PR DESCRIPTION
**Pull request by mfrachet**
Add a Searchbar component

Example:  https://design-system-git-add-searchbar-strapijs.vercel.app/?path=/story/searchbar--base

## API

```jsx
<SearchForm>
  <Searchbar
    name="searchbar"
    onClear={() => setValue('')}
    value={value}
    onChange={(e) => setValue(e.target.value)}
    clearLabel="Clearing the plugin search"
    placeholder="e.g: strapi-plugin-abcd"
  >
    Searching for a plugin
  </Searchbar>
</SearchForm>
```

### CODE REVIEW

**Comment by mfrachet** [comment]
cc @maevalienard I'm pushing the outline? However, I'm waiting for the update on specify concerning the shadow 😊

**Review by soupette — COMMENTED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]
LGTM good job @mfrachet !!

**Comment by maevalienard** [comment]
Awesome work Marvin, thank you!!!! The only thing I notice is the outline should have a 4px border-radius, otherwise it's perfect👌

**Comment by mfrachet** [comment]
> Awesome work Marvin, thank you!!!! The only thing I notice is the outline should have a 4px border-radius, otherwise it's perfect👌

Just pushed a fix for that 😊

**Comment by maevalienard** [comment]
Awesome, thank you!

**Pull request merged**
